/**
 * CALLBACK SON FUNCIONES QUE VIAJAN COMO PARAMETROS DE OTRAS FUNCIONES (DUNCION 2) Y QUE SE INVOCAN
 * CUANDO LA OTRA FUNCION (FUNCION 2) TERMINA DE HACER LO QUE SE HA PROGRAMADO
 */
setTimeout(() => {
    console.log("Este mensaje imprime el callback!");
}, 3000)